builds:
- env:
  - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
  ldflags:
    - "-w -s -X github.com/chanzuckerberg/czecs/version.GitSha={{.Commit}} -X github.com/chanzuckerberg/czecs/version.Version={{.Version}} -X github.com/chanzuckerberg/czecs/version.Dirty=false -X github.com/chanzuckerberg/czecs/version.Release=true"

archive:
  format_overrides:
  - goos: windows
    format: zip

changelog:
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^Initial commit$'
    - '^Merge pull request #.* from'
    - typo

brew:
  description: "ECS release management tool."
  github:
    owner: chanzuckerberg
    name: homebrew-czecs
  homepage: "https://github.com/chanzuckerberg/czecs"
  test: system "#{bin}/czecs version"
